apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhtap-demo-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-demo-python 
  name: rhtap-demo-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhtap-demo-python 
